version: 2

jobs:
  build:
    machine:
      docker_layer_caching: true
    working_directory: ~/codeclimate/codeclimate-ss-analyzer-wrapper
    steps:
      - checkout
      - run:
          name: Build
          command: make image
      - run:
          name: Test
          command: make test
